import pyautogui

SCREEN_W, SCREEN_H = pyautogui.size()

CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

SMOOTHING_FACTOR = 5  
CURSOR_FRAME_MARGIN = 100  

PINCH_THRESHOLD = 40  
SCROLL_SPEED = 50
GRAB_THRESHOLD = 60

WAKE_WORD = "glasses"
VOICE_TIMEOUT = 5
